import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const scaleFont = size => Math.round(size * (width / 375));

export const createStyles = (theme) => StyleSheet.create({
  Main: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    paddingBottom: 20,
  },
  headerSection: {
    paddingHorizontal: 16,
    paddingTop: 40,
    paddingBottom: 20,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 12, // Space between Avatar and Search
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  avatarText: {
    fontSize: scaleFont(18),
    fontWeight: '700',
    color: theme.colors.primary,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 48,
    elevation: 2, 
  },
  searchIcon: {
    marginRight: 8,
    color: theme.colors.textSecondary,
  },
  searchInput: {
    flex: 1,
    fontSize: scaleFont(13),
    color: '#1f2937',
  },
  logoutButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcomeSection: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
    paddingBottom: 12,
  },
  adminBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 8,
    alignSelf: 'flex-start',
    gap: 4,
  },
  adminBadgeText: {
    fontSize: scaleFont(10),
    fontWeight: '700',
    color: '#fff',
  },
  welcomeTitle: {
    fontSize: scaleFont(20),
    fontWeight: '800',
    color: '#fff',
    marginBottom: 4,
  },
  welcomeSubtitle: {
    fontSize: scaleFont(13),
    color: '#e3f2fd',
  },
  mapContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  mapPlaceholder: {
    height: 240,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mapPlaceholderText: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: '#4f46e5',
    marginTop: 12,
  },
  mapPlaceholderSubtext: {
    fontSize: scaleFont(11),
    color: '#6366f1',
    marginTop: 4,
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginHorizontal: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  legendText: {
    fontSize: scaleFont(10),
    color: '#fff',
    fontWeight: '600',
  },
  streetsSection: {
    paddingHorizontal: 16,
    marginTop: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: '#fff',
  },
  streetCount: {
    fontSize: scaleFont(11),
    color: '#e3f2fd',
    fontWeight: '600',
  },
  streetCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  streetContent: {
    flex: 1,
  },
  streetName: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 4,
  },
  floodRiskText: {
    fontSize: scaleFont(11),
    color: '#9ca3af',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusText: {
    fontSize: scaleFont(10),
    fontWeight: '600',
    color: '#fff',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: scaleFont(13),
    color: '#d1d5db',
    marginTop: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: scaleFont(18),
    fontWeight: '700',
    color: '#1f2937',
  },
  currentStreetName: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: '#1e40af',
    marginBottom: 12,
  },
  currentStatusLabel: {
    fontSize: scaleFont(11),
    fontWeight: '600',
    color: '#9ca3af',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  currentStatusBadge: {
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  currentStatusText: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: '#fff',
  },
  selectStatusLabel: {
    fontSize: scaleFont(13),
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 12,
  },
  statusOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  statusDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: 12,
  },
  statusOptionText: {
    fontSize: scaleFont(14),
    fontWeight: '600',
    color: '#1f2937',
  },
  cancelButton: {
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: scaleFont(14),
    fontWeight: '600',
    color: '#6b7280',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  settingsModal: {
    backgroundColor: theme.isDark ? '#1f2937' : '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '85%',
    paddingBottom: 20,
    elevation: 0,
    shadowColor: 'transparent',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: theme.isDark ? 'rgba(255,255,255,0.1)' : '#f1f5f9',
  },
  modalTitle: {
    fontSize: scaleFont(20),
    fontWeight: '800',
    color: theme.isDark ? '#fff' : '#1f2937',
  },
  settingsContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    padding: 16,
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : '#f8fafc',
    borderRadius: 20,
  },
  settingsAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  settingsAvatarText: {
    fontSize: scaleFont(22),
    fontWeight: '800',
    color: '#fff',
  },
  userDetails: {
    flex: 1,
  },
  userName: {
    fontSize: scaleFont(18),
    fontWeight: '700',
    color: theme.isDark ? '#fff' : '#1f2937',
  },
  userEmail: {
    fontSize: scaleFont(13),
    color: '#64748b',
    marginTop: 2,
  },
  settingsSection: {
    marginBottom: 16, 
  },
  sectionTitle: {
    fontSize: scaleFont(12),
    fontWeight: '700',
    color: '#94a3b8',
    marginBottom: 10,
    marginLeft: 4,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : '#f9fafb',
    borderRadius: 12,
    marginBottom: 6,
  },
  settingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  settingLabel: {
    fontSize: scaleFont(15),
    fontWeight: '600',
    color: theme.isDark ? '#e2e8f0' : '#334155',
    marginLeft: 14,
  },
  languageSelector: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  languageText: {
    fontSize: scaleFont(14),
    color: '#64748b',
    marginRight: 6,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    backgroundColor: theme.isDark ? 'rgba(239, 68, 68, 0.1)' : '#fff1f2',
    borderRadius: 16,
    marginTop: 10,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: theme.isDark ? '#7f1d1d' : '#fecaca',
  },
  logoutText: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: '#ef4444',
    marginLeft: 10,
  },
});